-- UX Evidence Collector — database schema
--
-- Run this once in the Supabase SQL editor (Dashboard → SQL → New query → paste → Run).
-- It is idempotent-ish: re-running on a fresh project is fine; on an existing one
-- the CREATE statements will error harmlessly.
--
-- Model:
--   libraries         one per team or person; every user gets a personal one on sign-up
--   library_members   who can see / edit a library (owner | editor | viewer)
--   invites           link-based invitations (the owner copies the link; no email sending needed)
--   evidence          the items. Screenshots live in the private storage bucket "evidence"
--
-- Security: row-level security everywhere. Nobody sees a library they are not a member of.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.libraries (
  id          uuid primary key default gen_random_uuid(),
  name        text not null check (char_length(name) between 1 and 80),
  owner_id    uuid not null references auth.users (id) on delete cascade,
  is_personal boolean not null default false,
  created_at  timestamptz not null default now()
);

create table public.library_members (
  library_id  uuid not null references public.libraries (id) on delete cascade,
  user_id     uuid not null references auth.users (id) on delete cascade,
  role        text not null check (role in ('owner', 'editor', 'viewer')),
  email       text not null,            -- denormalised so members can be listed without auth schema access
  created_at  timestamptz not null default now(),
  primary key (library_id, user_id)
);
create index library_members_user_idx on public.library_members (user_id);

create table public.invites (
  id          uuid primary key default gen_random_uuid(),
  library_id  uuid not null references public.libraries (id) on delete cascade,
  token       text not null unique default encode(gen_random_bytes(24), 'hex'),
  role        text not null default 'editor' check (role in ('editor', 'viewer')),
  label       text,                     -- optional note, e.g. "for Anna"
  created_by  uuid not null references auth.users (id) on delete cascade,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null default now() + interval '14 days',
  accepted_by uuid references auth.users (id),
  accepted_at timestamptz
);
create index invites_library_idx on public.invites (library_id);

create table public.evidence (
  id                uuid primary key,   -- generated by the client so offline captures keep their id
  library_id        uuid not null references public.libraries (id) on delete cascade,
  created_by        uuid references auth.users (id) on delete set null,

  url               text not null,
  domain            text not null,
  page_title        text not null default '',
  page_type         text not null default '',
  viewport          jsonb not null default '{"width":0,"height":0}',
  capture_mode      text not null default 'element' check (capture_mode in ('element', 'region', 'visible')),

  category          text not null default 'Other',
  observation       text not null,
  why_it_matters    text not null default '',
  notes             text not null default '',
  tags              text[] not null default '{}',

  screenshot_path   text not null,      -- storage object path inside bucket "evidence"
  thumbnail_path    text not null,
  screenshot_width  int  not null default 0,
  screenshot_height int  not null default 0,

  search_text       text not null default '',  -- maintained by trigger (see evidence_before_write)

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz          -- soft delete so other devices can pull the tombstone
);
create index evidence_library_updated_idx on public.evidence (library_id, updated_at);
create index evidence_library_created_idx on public.evidence (library_id, created_at desc) where deleted_at is null;
create index evidence_tags_idx on public.evidence using gin (tags);

-- ---------------------------------------------------------------------------
-- Helper functions (security definer so RLS policies can consult membership
-- without recursing into their own policies)
-- ---------------------------------------------------------------------------

create or replace function public.member_role(p_library uuid, p_user uuid)
returns text
language sql
security definer
stable
set search_path = public
as $$
  select role from public.library_members where library_id = p_library and user_id = p_user;
$$;

create or replace function public.is_member(p_library uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (select 1 from public.library_members where library_id = p_library and user_id = auth.uid());
$$;

create or replace function public.can_edit(p_library uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.library_members
    where library_id = p_library and user_id = auth.uid() and role in ('owner', 'editor')
  );
$$;

create or replace function public.is_owner(p_library uuid)
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.library_members
    where library_id = p_library and user_id = auth.uid() and role = 'owner'
  );
$$;

-- ---------------------------------------------------------------------------
-- Triggers
-- ---------------------------------------------------------------------------

-- Every new user gets a personal library (the on_library_created trigger
-- below makes them its owner).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.libraries (name, owner_id, is_personal)
  values ('My library', new.id, true);
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Creating a library makes the creator its owner.
create or replace function public.handle_new_library()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.library_members (library_id, user_id, role, email)
  values (new.id, new.owner_id, 'owner', coalesce((select email from auth.users where id = new.owner_id), ''))
  on conflict do nothing;
  return new;
end;
$$;

create trigger on_library_created
  after insert on public.libraries
  for each row execute function public.handle_new_library();

-- Keep updated_at honest on the server regardless of what the client sent,
-- and maintain the search haystack.
create or replace function public.evidence_before_write()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := greatest(now(), coalesce(new.updated_at, now()));
  new.search_text := lower(
    coalesce(new.observation, '') || ' ' || coalesce(new.why_it_matters, '') || ' ' ||
    coalesce(new.notes, '') || ' ' || coalesce(new.category, '') || ' ' ||
    array_to_string(coalesce(new.tags, '{}'), ' ') || ' ' || coalesce(new.domain, '') || ' ' ||
    coalesce(new.page_title, '') || ' ' || coalesce(new.url, '')
  );
  return new;
end;
$$;

create trigger evidence_before_write
  before insert or update on public.evidence
  for each row execute function public.evidence_before_write();

-- ---------------------------------------------------------------------------
-- RPCs
-- ---------------------------------------------------------------------------

-- Accept an invite link. Returns the library id. Anyone signed in with a valid,
-- unexpired, unused token joins with the invite's role.
create or replace function public.accept_invite(p_token text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  inv public.invites%rowtype;
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'Sign in first';
  end if;

  select * into inv from public.invites where token = p_token;
  if not found then
    raise exception 'This invite link is not valid';
  end if;
  if inv.accepted_at is not null then
    raise exception 'This invite link has already been used';
  end if;
  if inv.expires_at < now() then
    raise exception 'This invite link has expired';
  end if;

  insert into public.library_members (library_id, user_id, role, email)
  values (inv.library_id, uid, inv.role, coalesce((select email from auth.users where id = uid), ''))
  on conflict (library_id, user_id) do nothing;

  update public.invites set accepted_by = uid, accepted_at = now() where id = inv.id;

  return inv.library_id;
end;
$$;

-- Leave a library you are not the owner of.
create or replace function public.leave_library(p_library uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_owner(p_library) then
    raise exception 'Owners cannot leave their own library. Delete it or transfer ownership.';
  end if;
  delete from public.library_members where library_id = p_library and user_id = auth.uid();
end;
$$;

-- ---------------------------------------------------------------------------
-- Row-level security
-- ---------------------------------------------------------------------------

alter table public.libraries       enable row level security;
alter table public.library_members enable row level security;
alter table public.invites         enable row level security;
alter table public.evidence        enable row level security;

-- libraries
-- (owner_id check is needed so INSERT ... RETURNING works before the
--  membership trigger has run)
create policy "members can read libraries"
  on public.libraries for select
  using (owner_id = auth.uid() or public.is_member(id));

create policy "anyone signed in can create a library"
  on public.libraries for insert
  with check (auth.uid() = owner_id);

create policy "owners can rename libraries"
  on public.libraries for update
  using (public.is_owner(id))
  with check (public.is_owner(id));

create policy "owners can delete non-personal libraries"
  on public.libraries for delete
  using (public.is_owner(id) and not is_personal);

-- library_members
create policy "members can see who else is in the library"
  on public.library_members for select
  using (public.is_member(library_id));

create policy "owners manage members"
  on public.library_members for update
  using (public.is_owner(library_id))
  with check (public.is_owner(library_id));

create policy "owners remove members, members remove themselves"
  on public.library_members for delete
  using (public.is_owner(library_id) or user_id = auth.uid());

-- (inserts happen only through security-definer functions: triggers and accept_invite)

-- invites
create policy "owners see invites"
  on public.invites for select
  using (public.is_owner(library_id));

create policy "owners create invites"
  on public.invites for insert
  with check (public.is_owner(library_id) and created_by = auth.uid());

create policy "owners revoke invites"
  on public.invites for delete
  using (public.is_owner(library_id));

-- evidence
create policy "members read evidence"
  on public.evidence for select
  using (public.is_member(library_id));

create policy "editors insert evidence"
  on public.evidence for insert
  with check (public.can_edit(library_id));

create policy "editors update evidence"
  on public.evidence for update
  using (public.can_edit(library_id))
  with check (public.can_edit(library_id));

create policy "editors delete evidence"
  on public.evidence for delete
  using (public.can_edit(library_id));

-- ---------------------------------------------------------------------------
-- Storage: private bucket, object path = <library_id>/<evidence_id>/<file>
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('evidence', 'evidence', false, 10485760, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do nothing;

create policy "members read screenshots"
  on storage.objects for select
  using (bucket_id = 'evidence' and public.is_member(((storage.foldername(name))[1])::uuid));

create policy "editors upload screenshots"
  on storage.objects for insert
  with check (bucket_id = 'evidence' and public.can_edit(((storage.foldername(name))[1])::uuid));

create policy "editors replace screenshots"
  on storage.objects for update
  using (bucket_id = 'evidence' and public.can_edit(((storage.foldername(name))[1])::uuid));

create policy "editors delete screenshots"
  on storage.objects for delete
  using (bucket_id = 'evidence' and public.can_edit(((storage.foldername(name))[1])::uuid));
